title: Art by James TB
email: your-email@domain.com
description: >
  Art by Dunedin based artist James TB available for viewing or purchase.
baseurl: ""
url: "https:/jamestb.com"
markdown: kramdown
permalink: pretty
repository: FraserThompson/jamestbcom
defaults:
  - scope:
      path: ""
      type: art
    values:
      active: portfolio
      layout: art
      medium: Unspecified
      size: Unspecified
      price: Unspecified
collections:
  art:
    output: true