title: Art by James TB
email: your-email@domain.com
description: >
  Art by Dunedin based artist James TB available for viewing or purchase.
baseurl: ""
url: "https:/jamestb.com"
markdown: kramdown
permalink: pretty
defaults:
  - scope:
      path: ""
      type: art
    values:
      active: gallery
      layout: art
collections:
  art:
    output: true
  pages:
    output: true